//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kursach
{
    using System;
    using System.Collections.Generic;
    
    public partial class Othot
    {
        public int id { get; set; }
        public Nullable<System.DateTime> date_othot { get; set; }
        public Nullable<int> id_vizov { get; set; }
        public string diagnoz { get; set; }
        public Nullable<bool> is_dead { get; set; }
        public Nullable<bool> is_hospitalisir { get; set; }
    
        public virtual Vizov Vizov { get; set; }
    }
}
